### ISSUE TITLE
Failed propType: Invariant Violation prop type is invalid; it must be a function, usually from React.PropTypes. Check the render method of `ControllableWrapper`.

### ISSUE THREAD

**Issue by mderazon** [matthewwithanm/react-controllables#5]
I have the following toggle component

``` js
import React, {PropTypes, Component} from 'react/addons'
import controllable from 'react-controllables'
import shouldPureComponentUpdate from 'react-pure-render/function'

@controllable(['value'])
export default class toggle extends Component {

  shouldComponentUpdate = shouldPureComponentUpdate

  static propTypes = {
    value: PropTypes.string,
    onChange: PropTypes.func.required
  }

  render () {
    return (
      <div className='ui toggle checkbox'>
        <input id='toggle' type='checkbox' onChange={this.props.onChange} checked={this.props.value} />
        <label htmlFor='toggle' ></label>
      </div>
    )
  }
}
```

Getting the following error

> Failed propType: Invariant Violation: toggle: prop type `onChange` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `ControllableWrapper`.

Am I using it the wrong way?

Thanks

**Comment by matthewwithanm** [comment]
Nope, you're using it right! This is just a React error saying that one of the values in your `propTypes` dict is no good…

If I open up a console, `PropTypes.string` is a function, so that's not the problem, but `PropTypes.func.required` is `undefined`—woops! I think you meant `PropTypes.func.isRequired` (:

**Comment by mderazon** [comment]
Ahhh!

Tricky error message,
could have just said "PropTypes.func.required is undefined" or something like that :-)

Thanks, and thank for the this cool module as well :+1:

**Comment by matthewwithanm** [comment]
😊 Thanks!

**Comment by MHerszak** [comment]
Thank you @matthewwithanm :+1:

**Comment by philstrong** [comment]
PropTypes.boolean can get you as well ... it's `bool`

**Comment by rfreitas** [comment]
hmm, shouldn't this be better designed then? as in give out a warning if `undefined` is passed as a value?

I got the same bug but by referencing `PropTypes.function` and the error was the same: `prop type is invalid; it must be a function`, talk about misleading.. 

Also, it's inconsistent because it's `PropTypes.string`, `PropTypes.object`, `PropTypes.number`, not `str`, `obj`, `num`.

**Comment by konekoya** [comment]
@philstrong Thanks, It's really tricky. Have spent quite some time searching on this.

**Comment by gibbitz** [comment]
No one has mentioned it here, but my problem was when using redux form `propTypes` I copy pasta'd to define a react `PropTypes` prop and was stung. `propTypes.string` is undefined where `PropTypes.string` is a function. Case matters :(

**Comment by johannesnagl** [comment]
Also coming from google to here. My problem was a mis-spelling of `isRequired`. 😨 🤕

**Comment by tommyalvarez** [comment]
Another one from google... but mine was tricker i confused 

```
class.defaultProps = {
loading: false
}

```
with 
```
class.propTypes = {
loading: false
}
```

And since prop loading was in defaultProps as well as propTypes it was confusing me. I wrote class.propTypes twice lol

**Comment by yashhy** [comment]
My issue was, I have used **.oneOf** as an array instead of a function ☹️

**Like :** 
PropTypes.oneOf[('top', 'right', 'bottom', 'left')]

**Instead of :** 
PropTypes.oneOf(['top', 'right', 'bottom', 'left'])
